### ISSUE TITLE
when Load InsightFace (PuLID Flux), ComfyUI Error Report get erro. Help! 

### ISSUE THREAD

**Issue by ohahaps2** [balazik/ComfyUI-PuLID-Flux#15]
ComfyUI Error Report
## Error Details
- **Node Type:** PulidFluxInsightFaceLoader
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace
```
  File "H:\sd3\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd3\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd3\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "H:\sd3\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd3\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux\pulidflux.py", line 196, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\sd3\python_embeded\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models

**Comment by balazik** [comment]
Hi @ohahaps2, check if you did not skip the step with downloading Insightface models:
- InsightFace with [AntelopeV2](https://huggingface.co/MonsterMMORPG/tools/tree/main), the unzipped models should be placed in ComfyUI/models/insightface/models/antelopev2

**Comment by ohahaps2** [comment]
yes, all files in antelopev2,          glintr100.onnx 1k3d68.onnx 2d106det.onnx scrfd_10g_bnkps.onnx glintr100.onnx


> Hi @ohahaps2, check if you did not skip the step with downloading Insightface models:您好，请检查您是否没有跳过下载 Insightface 模型的步骤：
> 
> * InsightFace with [AntelopeV2](https://huggingface.co/MonsterMMORPG/tools/tree/main), the unzipped models should be placed in ComfyUI/models/insightface/models/antelopev2InsightFace with [AntelopeV2](https://huggingface.co/MonsterMMORPG/tools/tree/main) ，解压后的模型应放置在 ComfyUI/models/insightface/models/antelopev2 中

**Comment by balazik** [comment]
Thumbs up means probably helped, closing. :)
