### ISSUE TITLE
PuLid Nodes Not loading

### ISSUE THREAD

**Issue by Stronm** [balazik/ComfyUI-PuLID-Flux#18]
I followed every instruction 
Installed the ComfyUI-PuLID-Flux in  Custom node folder .
Downloaded all extra requirements
but its not loading

![image](https://github.com/user-attachments/assets/9c0118e3-226a-49ff-baaa-364ab451f098)

![brave_uXFn5dZ3ZJ](https://github.com/user-attachments/assets/59732323-82e9-4f35-965a-a41a2f2b3bb1)

**Comment by balazik** [comment]
Did you also install all Python packages in your Python environment that are mentioned in requirements.txt ?

**Comment by balazik** [comment]
@Stronm 
Could you please let me know which version of ComfyUI you have installed? Is it the portable version or the standard one? Additionally, if you have installed the requirements.txt, I would greatly appreciate it if you could copy and paste the log when ComfyUI starts. This will help me identify what went wrong.

**Comment by Stronm** [comment]
> @Stronm Could you please let me know which version of ComfyUI you have installed? Is it the portable version or the standard one? Additionally, if you have installed the requirements.txt, I would greatly appreciate it if you could copy and paste the log when ComfyUI starts. This will help me identify what went wrong.

Yes i have installed all python packages needed , 
Actually  i was running comfy and forge till few days back , wanted to check out PuLid so removed everything  and did a clean install , 
As for the comfyUI version its the latest one

**Comment by balazik** [comment]
@Stronm can you please send me the log that appears at the start of comfy ? (when you run it in linux terminal or windows cmd).
There should be some hints for me, at least why it failed to load the nodes. (before anonymize the paths if you care, I need just the errors)

**Comment by Stronm** [comment]
[comfyui.log](https://github.com/user-attachments/files/17259218/comfyui.log)
[comfyui.prev.log](https://github.com/user-attachments/files/17259220/comfyui.prev.log)
[comfyui.prev2.log](https://github.com/user-attachments/files/17259221/comfyui.prev2.log)


> @Stronm can you please send me the log that appears at the start of comfy ? (when you run it in linux terminal or windows cmd). There should be some hints for me, at least why it failed to load the nodes. (before anonymize the paths if you care, I need just the errors)

**Comment by balazik** [comment]
@Stronm 

In the first log: `No module named 'insightface'`
So you didn't install all what is mentioned here:
[https://github.com/balazik/ComfyUI-PuLID-Flux/blob/master/requirements.txt](https://github.com/balazik/ComfyUI-PuLID-Flux/blob/master/requirements.txt)

Install all the packages. It is mentioned in the Install instructions. You just installed ComfyUI requirements but not this repo requirements. Happens to many users. All plugins have its own ;)

**Comment by balazik** [comment]
@Stronm let me know if it helped.

**Comment by Stronm** [comment]
![image](https://github.com/user-attachments/assets/82a654d9-8067-4fd5-ad32-a7b212fc737d)
its all installed

**Comment by Stronm** [comment]
Still 
![image](https://github.com/user-attachments/assets/56a84210-8d04-4c5b-9154-dcb8029eac0a)

**Comment by Stronm** [comment]
![image](https://github.com/user-attachments/assets/5b4093e7-0a81-4482-b5b0-59c7aa353cb7)
i went ahead and installed it separately 
but it still didn't work , 
as u can see its the PuLid nodes that aint showing up.

**Comment by Stronm** [comment]
**

> [2024-10-04 19:54]    0.0 seconds (IMPORT FAILED): E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux

**

**Comment by balazik** [comment]
@Stronm 
Yes but from the logs that you send me the reason is written above that!
```
[2024-10-04 18:01] Cannot import E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux module for custom nodes: No module named 'insightface'
```
Does ComfyUI portable use the system python packages ? Does it not come with its own virtual environment ? (I never used portable version before, so that's why asking)

**Comment by Stronm** [comment]
ComfyUI Portable operates with its own embedded Python environment
So 

> pip install insightface 


should have worked in this case

**Comment by Stronm** [comment]
![image](https://github.com/user-attachments/assets/32cb61f1-cec5-4a12-a1fc-d792ff1d3235)
What kind of madness is this

**Comment by balazik** [comment]
Python madness :) But we can solve it.
Its normal because it uses its own copy of python interpreter that has its own copy of pip, so that why it didn't work.
You just need to install the packages to the portable python copy. And it will work.

Now I begin to see why other people have problems with portable version. But at least now I can help them.
If you install the packages there please let me know if it helped.

**Comment by Stronm** [comment]
> Python madness :) But we can solve it. Its normal because it uses its own copy of python interpreter that has its own copy of pip, so that why it didn't work. You just need to install the packages to the portable python copy. And it will work.
> 
> Now I begin to see why other people have problems with portable version. But at least now I can help them. If you install the packages there please let me know if it helped.
Man it took me a while to individually install them 1 by 1 to python embeded 
Faced few issues while installing 
facexlib
insightface

**But its working now**

**Comment by balazik** [comment]
Good, I'm glad that it worked out. Closing

**Comment by ksalling** [comment]
For anyone using the portable version of comfyui... navigate to the python_embedded directory and and use the following command to install the necessary packages to the embedded python install: python.exe -s -m pip install facexlib insightface onnxruntime onnxruntime-gpu ftfy timm

**Comment by PrashanthRushi** [comment]
![Screenshot 2024-12-13 225257](https://github.com/user-attachments/assets/0f0d9668-fb91-4248-a0f7-47c1500bf597)
getting this error while installing the pulID
 please help me

**Comment by Stronm** [comment]
> navigate to the python_embedded directory and and use the following command to install the necessary packages to the embedded python install: python.exe -s -m pip install facexlib insightface onnxruntime onnxruntime-gpu ftfy timm



> ![Screenshot 2024-12-13 225257](https://private-user-images.githubusercontent.com/124128476/395645388-0f0d9668-fb91-4248-a0f7-47c1500bf597.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3OTY0NjksIm5iZiI6MTczNjc5NjE2OSwicGF0aCI6Ii8xMjQxMjg0NzYvMzk1NjQ1Mzg4LTBmMGQ5NjY4LWZiOTEtNDI0OC1hMGY3LTQ3YzE1MDBiZjU5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QxOTIyNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2QzZGQyZDI4NjVmMmExN2M1OTVmYzkyNjJlNDY5NDFiNTBiN2Y1NGRmNTJhNWIyM2Y5ODVjZDAxNGNlMTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qRk43JRLFks60DrtoYluP1f5-9-ljQ36ibFizvnpwL8) getting this error while installing the pulID please help me
