### ISSUE TITLE
how do you train the PULID model?

### ISSUE THREAD

**Issue by wuutiing** [balazik/ComfyUI-PuLID-Flux#21]
It seems `PerceiverAttentionCA` makes it reasonable to do attn-op between face features and flux latents, i'm curious how do you train that, would you mind share your experiences, thank you a lot!

**Comment by balazik** [comment]
The model was not trained by me! When you look at the Credits section of the REAME.md, you will see this link:
[https://github.com/ToTheBeginning/PuLID](https://github.com/ToTheBeginning/PuLID)
Go  and ask the authors.
