### ISSUE TITLE
does not support pulid_v1？

### ISSUE THREAD

**Issue by Songssx** [balazik/ComfyUI-PuLID-Flux#3]
After testing, it was found that the model does not support pulid_v1, and an error message will appear saying 'PulidFluxModel' object has no attribute 'id_adapter'. I am not sure if this is due to the issue with torch2.4.1+cu124

**Comment by balazik** [comment]
@Songssx This node is explicitly for PuLID Flux! Not for SDXL. If you want to use the older you can use this repo:
https://github.com/cubiq/PuLID_ComfyUI

At the moment, I don't see the point in also supporting the old model. Each flow has only one type of model loaded in 99% cases (SDXL or FLux or SD3 etc.). If a mix is ​​needed, the nodes from PuLID_ComfyUI and ComfyUI-PuLID-Flux are compatible, i.e. PulidFluxEvaClipLoader, PulidFluxInsightFaceLoader can be used for both models PuLID (SDXL, Flux)
